name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages branch
      run: git checkout gh-pages

    - name: Copy required files
      run: |
        git checkout main -- data scripts package.json yarn.lock .prettierrc.js
        echo "Unstage all files"
        git reset

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Run split script
      run: |
        echo "Running dapi pricing split script"
        node scripts/split-dapi-pricing.js

    - name: Commit and push if changes detected
      run: |
        if [ -n "$(git status data --porcelain)" ]; then
          echo "Changes detected in gh-pages branch."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          echo "Commiting file"
          git commit -m "Update data file(s)"
          echo "Pushing commit"
          git push
        else
          echo "No changes to commit and push."
        fi
