name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages branch
      run: git checkout gh-pages

    - name: Copy new files to data folder
      run: |
        git checkout main -- data

    - name: Commit and push if there are changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected in gh-pages branch."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update data file(s)"
          git push
        else
          echo "No changes to commit and push."
        fi