name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages branch
      run: git checkout gh-pages-test

    - name: Copy required files
      run: |
        git checkout main -- data scripts package.json yarn.lock
        echo "Unstage all files"
        git reset

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Check if there are changes in gh-pages branch
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected in gh-pages branch."
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Running dapi pricing split script"
          node scripts/split-dapi-pricing.js
          git add data
          git commit -m "Update data file(s)"
          git push
        else
          echo "No changes to commit and push."
        fi